"use client";

import { createTheme, ThemeProvider } from "@mui/material";
import "./globals.css";

// export const metadata = {
//   title: "Sky Textiles",
//   description: "Generated by create next app",
// };

const theme = createTheme({
  breakpoints: {
    values: {
      xs: 0,
      sm: 314,
      smm: 530,
      md: 768,
      lg: 1024,
      xl: 1220,
      xll: 1440,
      xxl: 1600,
    },
  },
});

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <ThemeProvider theme={theme}>
        <body>{children}</body>
      </ThemeProvider>
    </html>
  );
}
